### PR TITLE
Add list of acronyms to thesis template

### PR DESCRIPTION
**Pull request by Incredible-O**

### CODE REVIEW

**Comment by michaelroland** [comment]
**Discussion:** I'm not quite sure if it's agood idea to add acronyms to the thesis example.

Pro:
- It's probably good to help students get this right, if they need it.

Contra:
- A list of acronyms is often not necessary at all, and I don't like the idea of having this part of the starting example, since students will probably blindly pick this up and add it to their thesis.

**Comment by michaelroland** [comment]
If this example is added, the following items need to be resolved:

- [x] List of abbreviations should be in the front matter after the ToC, immediately after LoT and LoF (and LoL)
- [x] Sectioning should be unnumbered, use `\addchap{}`
- [ ] I wonder if the `glossaries` package would be the better choice instead of `acronym` ...
- [x] Should the example code be commented out (just like the LoF and LoT example)?

**Comment by Incredible-O** [comment]
> A list of acronyms is often not necessary at all, and I don't like the idea of having this part of the starting example, since students will probably blindly pick this up and add it to their thesis.

I agree, a list of acronyms isn't always necessary.

> I wonder if the `glossaries` package would be the better choice instead of `acronym` ...

I'm fine with both packages -- personally, I'd prefer `acronym` though. Please correct me if I'm wrong, but `glossaries` seems to depend on an external script (`makeglossaries`)?

**Comment by michaelroland** [comment]
> I'm fine with both packages -- personally, I'd prefer `acronym` though. Please correct me if I'm wrong, but `glossaries` seems to depend on an external script (`makeglossaries`)?

Fair point. This would make usage of the template a lot more complex ... `acronym` it is then.

I'm still not happy with the file name for the list of acronyms, need to think if changing the whole numbering scheme or adding a second file with 00- or not using a prefix at all would be best ... what do you think?

**Comment by Incredible-O** [comment]
> I'm still not happy with the file name for the list of acronyms, need to think if changing the whole numbering scheme or adding a second file with 00- or not using a prefix at all would be best ... what do you think?

Not using a prefix would be fine IMO -- the list of acronyms isn't a "regular" chapter after all. I think the current numbering scheme is fine as-is, with the prefixes `01`, `02`... `10` (and so on) being reserved for _actual_ content.
I agree that the filename `90-acronyms.tex` is a bit misleading though (considering the list of acronyms has been moved to the beginning of the document).

**Pull request merged**
